# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:26658"
moniker = "anonymous"
fast_sync = true
db_backend = "goleveldb"
log_level = "state:info,consensus:debug,*:error"

[rpc]
laddr = "tcp://0.0.0.0:26657"

[p2p]
laddr = "tcp://0.0.0.0:26656"
seeds = ""
flush_throttle_timeout = 10

[consensus]
timeout_commit = 10
skip_timeout_commit = true
peer_gossip_sleep_duration = 10
