version: '3.7'
x-node:
  &default-node
  build: ./node
  env_file: ./secret/node.env
  secrets:
    - authorized_keys
  privileged: true
  tty: true
  tmpfs:
    #- /run:size=100M
    - /run/lock:size=100M
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  networks:
    - jepsen
  ports:
    - ${JEPSEN_PORT:-22}

secrets:
  authorized_keys:
    file: ./secret/authorized_keys

services:
  control:
    container_name: jepsen-control
    hostname: control
    depends_on:
      - n1
      - n2
      - n3
      - n4
      - n5
    build: ./control
    env_file: ./secret/control.env
    privileged: true
    ports:
      - "8080"
    networks:
      jepsen:
        ipv4_address: 172.26.0.16
  n1:
    << : *default-node
    container_name: jepsen-n1
    hostname: n1
    ports:
      - "10002"
      - "10000"
      - "1478"
    networks:
      jepsen:
        ipv4_address: 172.26.0.11
  n2:
    << : *default-node
    container_name: jepsen-n2
    hostname: n2
    ports:
      - "10002"
      - "10000"
      - "1478"
    networks:
      jepsen:
        ipv4_address: 172.26.0.12
  n3:
    << : *default-node
    container_name: jepsen-n3
    hostname: n3
    ports:
      - "10002"
      - "10000"
      - "1478"
    networks:
      jepsen:
        ipv4_address: 172.26.0.13
  n4:
    << : *default-node
    container_name: jepsen-n4
    hostname: n4
    ports:
      - "10002"
      - "10000"
      - "1478"
    networks:
      jepsen:
        ipv4_address: 172.26.0.14
  n5:
    << : *default-node
    container_name: jepsen-n5
    hostname: n5
    ports:
      - "10002"
      - "10000"
      - "1478"
    networks:
      jepsen:
        ipv4_address: 172.26.0.15

networks:
  jepsen:
    driver: bridge
    ipam:
      config:
      - subnet: 172.26.0.0/24
